[phases.setup]
nixPkgs = ["python311", "libGL", "libglib", "libxcb", "xorg.libX11", "xorg.libXext", "xorg.libXrender"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python app.py"